### ISSUE TITLE
Detailed native ("dockerless") installation guide

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/docs#107]
- install node
- install go
- install xud
- install connext
- install lnd's
- connect em (xud.conf, copying tls.certs et al)

**Comment by michael1011** [comment]
Setting up XUD natively is tricky.

> install node

I'd recommend installing the latest Node *LTS* and NPM from here: https://nodejs.org/en/
For Linux distros: `Other Downloads` -> `Installing Node.js via package manager`
On Windows: https://chocolatey.org/packages/nodejs-lts
On Mac OS: Homebrew?

> install go

On Ubuntu or on distros that have Snap installed: `sudo snap install go --classic` (*I know. Snap sucks but installing Go with it is just too convenient*)
Else: https://golang.org/dl/

> install xud

Git clone the repo or download the `tgz` archive from the the [page of the latest release](https://github.com/ExchangeUnion/xud/releases)

In the repo folder `npm i` (if you used the archive just `npm i --prod`)

If you cloned the repo *and* are on an architecture that is not 64 bit x86 (effectively 32 bit or 64 bit ARM), you have to remove the `grpc-tools` dev dependency: https://github.com/ExchangeUnion/xud-docker/blob/master/images/xud/Dockerfile.aarch64#L13

If you cloned the repo you also have to execute `npm run compile` and `npm run compile:seedutil` afterwards

**Question:** how does the seedutil work in the `tgz` archive?

> install connext

Clone repo, checkout latest release, `npm i` and `npm run build`

> install lnd's

Pretty much straightforward. You just need to make sure that the LND build you run was compiled with `invoicesrpc` (support for hold invoices)

> connect em (xud.conf, copying tls.certs et al)

I used systemd to run XUD and Connext

`connext.service`:

```
[Unit]
Description=Connext

[Service]
User=xud
Group=xud
Type=simple
Environment="NODE_ENV=production"
Environment="CONNEXT_NODE_URL=https://connext.boltz.exchange"
Environment="CONNEXT_ETH_PROVIDER_URL=http://127.0.0.1:8545"
Environment="LEGACY_MODE=true"
WorkingDirectory=/home/xud/connext/
ExecStart=node /home/xud/connext/build/src/index.js
KillMode=process
KillSignal=SIGINT
```

`xud.service`:

```
[Unit]
Description=XUD daemon

[Service]
User=xud
Group=xud
Type=simple
Environment=NODE_ENV=production
ExecStart=/home/xud/xud/bin/xud --mainnet
KillMode=process
KillSignal=SIGINT
```

My XUD config file:

```toml
mainnet = true

[p2p]
tor = true
torport = 9050

[raiden]
disable = true

[connext]
disable = false
host = "localhost"
port = 5000
webhookhost = "localhost"
webhookport = 8887

[lnd.BTC]
disable = false
host = "10.0.1.14"
certpath = "/home/xud/.lnd/tls.cert"
macaroonpath = "/home/xud/.lnd/admin.macaroon"

[lnd.LTC]
disable = true
```

The `[p2p]` section requires TOR to be installed and running on the XUD machine. You have to set that up to be able to connect to other TOR XUD nodes

And as a nice finishing touch a alias for xucli in the `.bashrc` file of the `xud` user:

```bash
alias xucli='/home/xud/xud/bin/xucli -p 8886'
```
